name: E2E for Countries API web App on Chrome
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*"

jobs:
  install:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          headless: true
          start: npm start
          wait-on: "http://localhost:3000"
