name: E2E for Countries API web App on Chrome
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean npm cache and install dependencies
        uses: npm ci
          yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./site
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
