name: E2E for Countries API web App on Chrome
on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      CI: false # Explicitly set CI to false for the entire job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean npm cache and install dependencies
        run: |
          npm ci
          yarn install

      - name: Build app (disable CI warnings)
        run: yarn build # CI=false is already set as an environment variable

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./site
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
